### ISSUE TITLE
用户库和内核的 read/write 中，stdin 与 stdout 写反了

### ISSUE THREAD

**Issue by scPointer** [YdrMaster/rCore-Tutorial-in-single-workspace#7]
在 `/ch6/src/main.rs:320` 的 `fn write(&self, _caller: Caller, fd: usize, buf: usize, count: usize)` 和  `/ch6/src/main.rs:360` 的 `fn read(&self, _caller: Caller, fd: usize, buf: usize, count: usize)` 中，特殊判定了文件描述符为 0 时当作标准输出处理，为 1 时当作标准输入处理。但实际上应该是反过来，即 0 是标准输入，1 是标准输出。

这个问题之所以没有暴露出来，是因为 `/user/src/lib.rs` 里的 `getchar()` 和 `put_char()` 也写反了，刚好负负得正。建议这两边都改成常量的 `STDIN` 和 `STDOUT`，而不是用 `magic number` 来写了。

顺便，在 `/ch6/src/process.rs:91` 的 `pub fn from_elf(elf: ElfFile)` 中，标准输入和输出的写法是对的，但实际处理 `read / wirte` 没有用到。

再顺便，在 `/ch7` 的对应文件里，因为暂时不影响其他模块，所以还留着上面的 bug，可以一并改掉

**Comment by YdrMaster** [comment]
感谢，已改
